[package]
name = "ogexplain-optimizer"
version.workspace = true
edition.workspace = true

[dependencies]
ogexplain-core = { path = "../ogexplain-core" }
ogsql-parser = { git = "https://github.com/c2j/ogsql-parser", tag = "v0.8.31" }
metamorphosis-core = { git = "https://github.com/c2j/metamorphosis.git", rev = "0a34a744435dc0a1e97d7378800e19948d17049e", package = "metamorphosis-core" }
metamorphosis-qed = { git = "https://github.com/c2j/metamorphosis.git", rev = "0a34a744435dc0a1e97d7378800e19948d17049e", package = "metamorphosis-qed", optional = true }
metamorphosis-verieql = { git = "https://github.com/c2j/metamorphosis.git", rev = "0a34a744435dc0a1e97d7378800e19948d17049e", package = "metamorphosis-verieql", optional = true }
metamorphosis-rules = { git = "https://github.com/c2j/metamorphosis.git", rev = "0a34a744435dc0a1e97d7378800e19948d17049e", package = "metamorphosis-rules" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tracing = "0.1"

[features]
default = ["verify"]
verify = ["dep:metamorphosis-qed", "dep:metamorphosis-verieql"]
