use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let regress_root = PathBuf::from(&manifest_dir).join("tests/regress");

    println!("cargo:rerun-if-changed=tests/regress");

    let mut cases: Vec<(String, PathBuf)> = Vec::new();
    if regress_root.exists() {
        walk(&regress_root, &mut cases);
    }
    cases.sort();

    let mut src = String::new();
    src.push_str("// Auto-generated by build.rs — DO NOT EDIT.\n\n");

    if cases.is_empty() {
        src.push_str("#[test] fn no_regress_cases_present() {\n");
        src.push_str(
            "    panic!(\"tests/regress/ has no case.toml files — directory walk returned nothing\");\n",
        );
        src.push_str("}\n");
    } else {
        for (fn_name, abs_path) in cases {
            let rel_path = abs_path
                .strip_prefix(&manifest_dir)
                .unwrap_or(&abs_path)
                .to_string_lossy()
                .to_string();
            src.push_str(&format!(
                "#[test] fn {fn_name}() {{ run_case_with_report(std::path::PathBuf::from({rel_path:?})); }}\n"
            ));
        }
    }

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let target = PathBuf::from(&out_dir).join("regress_generated_tests.rs");
    if let Err(e) = fs::write(&target, &src) {
        panic!("failed to write {}: {}", target.display(), e);
    }
}

fn walk(root: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(rd) = fs::read_dir(root) else {
        return;
    };
    for ent in rd.flatten() {
        let p = ent.path();
        if !p.is_dir() {
            continue;
        }
        if p.join("case.toml").is_file() {
            let dir_name = p
                .file_name()
                .map(|n| n.to_string_lossy().into_owned())
                .unwrap_or_default();
            let fn_name = sanitize_fn_name(&dir_name);
            out.push((fn_name, p));
        } else {
            walk(&p, out);
        }
    }
}

fn sanitize_fn_name(dir_name: &str) -> String {
    dir_name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}
