#[derive(Debug, Clone, PartialEq, Eq)]
#[allow(dead_code)]
pub enum Action {
    ParseExplain,
    LoadFile(String),
    TreeUp,
    TreeDown,
    TreeToggle,
    TreeExpandAll,
    TreeCollapseAll,
    DetailUp,
    DetailDown,
    NextPanel,
    PrevPanel,
    ToggleFindings,
    Quit,
    Resize(u16, u16),
    ClearInput,
    ToggleHelp,
    ToggleRawView,
    DetailPageUp,
    DetailPageDown,
    DetailHome,
    DetailEnd,
    TreeTop,
    TreeBottom,
    NextPlan,
    PrevPlan,
    ToggleComplexity,
}
